/*
  This file is used to define the themes for Vuetify.
  The light theme is defined here.
  The dark theme is defined in the same way.

  Defined colors must be synced with the colors, defined in color variables.
  '@/assets/styles/variables/_colors.scss'
 */

import type { ThemeDefinition } from 'vuetify'
import { colors } from '../../static/DesignTokens'

export const light: ThemeDefinition = {
  dark: false,
  colors: {
    // This is the default color palette for Vuetify.

    // 'background: #FFFFFF' would be interpolated as var(--v-theme-background) as 255, 255, 255
    // use inside rgb() or rgba() functions
    // rgba(var(--v-theme-background), 0.87)

    background: colors.base.white,
    'on-background': colors.grayLight[900],
    surface: colors.base.white,
    'on-surface': colors.grayLight[900],
    'surface-bright': colors.base.white,
    'on-surface-bright': colors.grayLight[900],
    'surface-light': colors.grayLight[50],
    'on-surface-light': colors.grayLight[900],
    'surface-variant': colors.grayLight[50],
    'on-surface-variant': colors.grayLight[900],
    primary: colors.brand[600],
    'on-primary': colors.base.white,
    'primary-darken-1': colors.brand[700],
    'on-primary-darken-1': colors.base.white,
    secondary: colors.brand[500],
    'on-secondary': colors.base.white,
    'secondary-darken-1': colors.brand[400],
    'on-secondary-darken-1': colors.base.white,
    error: colors.error[600],
    'on-error': colors.base.white,
    success: colors.success[600],
    'on-success': colors.base.white,
    warning: colors.warning[600],
    'on-warning': colors.base.white,
    'brand-section': colors.brand[800],
    'on-brand-section': colors.base.white,
  },
  variables: {
    // This is the set of variables that defined in our design system.
    // also other non-color variables can be defined here.

    // 'my-crazy-variable': 42, would be interpolated as var(--v-my-crazy-variable)
    // colors would be interpolated as 255, 255, 255 and should be used inside rgb() or rgba() functions
    // rgba(var(--v-color-gray-950), 0.87)

    /* Override Vuetify opacity variables */
    'border-opacity': 0.12,
    'high-emphasis-opacity': 0.87,
    'medium-emphasis-opacity': 0.60,
    'disabled-opacity': 0.38,
    'idle-opacity': 0.04,
    'hover-opacity': 0,
    'focus-opacity': 0.12,
    'selected-opacity': 0.08,
    'activated-opacity': 0,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,

    /* Base colors */
    'color-base-white': colors.base.white,
    'color-base-black': colors.base.black,
    'color-base-transparent': colors.base.transparent,

    /* Gray colors */
    'color-gray-25': colors.grayLight[25],
    'color-gray-50': colors.grayLight[50],
    'color-gray-100': colors.grayLight[100],
    'color-gray-200': colors.grayLight[200],
    'color-gray-300': colors.grayLight[300],
    'color-gray-400': colors.grayLight[400],
    'color-gray-500': colors.grayLight[500],
    'color-gray-600': colors.grayLight[600],
    'color-gray-700': colors.grayLight[700],
    'color-gray-800': colors.grayLight[800],
    'color-gray-900': colors.grayLight[900],
    'color-gray-950': colors.grayLight[950],

    /* Brand colors */
    'color-brand-25': colors.brand[25],
    'color-brand-50': colors.brand[50],
    'color-brand-100': colors.brand[100],
    'color-brand-200': colors.brand[200],
    'color-brand-300': colors.brand[300],
    'color-brand-400': colors.brand[400],
    'color-brand-500': colors.brand[500],
    'color-brand-600': colors.brand[600],
    'color-brand-700': colors.brand[700],
    'color-brand-800': colors.brand[800],
    'color-brand-900': colors.brand[900],
    'color-brand-950': colors.brand[950],

    /* Error colors */
    'color-error-25': colors.error[25],
    'color-error-50': colors.error[50],
    'color-error-100': colors.error[100],
    'color-error-200': colors.error[200],
    'color-error-300': colors.error[300],
    'color-error-400': colors.error[400],
    'color-error-500': colors.error[500],
    'color-error-600': colors.error[600],
    'color-error-700': colors.error[700],
    'color-error-800': colors.error[800],
    'color-error-900': colors.error[900],
    'color-error-950': colors.error[950],

    /* Success colors */
    'color-success-25': colors.success[25],
    'color-success-50': colors.success[50],
    'color-success-100': colors.success[100],
    'color-success-200': colors.success[200],
    'color-success-300': colors.success[300],
    'color-success-400': colors.success[400],
    'color-success-500': colors.success[500],
    'color-success-600': colors.success[600],
    'color-success-700': colors.success[700],
    'color-success-800': colors.success[800],
    'color-success-900': colors.success[900],
    'color-success-950': colors.success[950],

    /* Warning colors */
    'color-warning-25': colors.warning[25],
    'color-warning-50': colors.warning[50],
    'color-warning-100': colors.warning[100],
    'color-warning-200': colors.warning[200],
    'color-warning-300': colors.warning[300],
    'color-warning-400': colors.warning[400],
    'color-warning-500': colors.warning[500],
    'color-warning-600': colors.warning[600],
    'color-warning-700': colors.warning[700],
    'color-warning-800': colors.warning[800],
    'color-warning-900': colors.warning[900],
    'color-warning-950': colors.warning[950],

    /* Text color variables */
    'text-primary': colors.grayLight[900],
    'text-primary-on-brand': colors.base.white,
    'text-secondary': colors.grayLight[700],
    'text-secondary-hover': colors.grayLight[800],
    'text-secondary-on-brand': colors.brand[200],
    'text-tertiary': colors.grayLight[600],
    'text-tertiary-hover': colors.grayLight[700],
    'text-tertiary-on-brand': colors.brand[200],
    'text-quaternary': colors.grayLight[500],
    'text-quaternary-on-brand': colors.brand[300],
    'text-white': colors.base.white,
    'text-disabled': colors.grayLight[500],
    'text-placeholder': colors.grayLight[500],
    'text-placeholder-subtle': colors.grayLight[300],
    'text-brand-primary': colors.brand[900],
    'text-brand-secondary': colors.brand[700],
    'text-brand-tertiary': colors.brand[600],
    'text-brand-tertiary-alt': colors.brand[600],
    'text-error-primary': colors.error[600],
    'text-warning-primary': colors.warning[600],
    'text-success-primary': colors.success[600],

    /* Border color variables */
    'border-primary': colors.grayLight[300],
    'border-secondary': colors.grayLight[200],
    'border-tertiary': colors.grayLight[100],
    'border-disabled': colors.grayLight[300],
    'border-disabled-subtle': colors.grayLight[200],
    'border-brand': colors.brand[300],
    'border-brand-solid': colors.brand[600],
    'border-brand-solid-alt': colors.brand[600],
    'border-error': colors.error[300],
    'border-error-solid': colors.error[600],

    /* Foreground color variables */
    'fg-primary': colors.grayLight[900],
    'fg-secondary': colors.grayLight[700],
    'fg-secondary-hover': colors.grayLight[800],
    'fg-tertiary': colors.grayLight[600],
    'fg-tertiary-hover': colors.grayLight[700],
    'fg-quaternary': colors.grayLight[500],
    'fg-quaternary-hover': colors.grayLight[600],
    'fg-quinary': colors.grayLight[400],
    'fg-quinary-hover': colors.grayLight[500],
    'fg-senary': colors.grayLight[300],
    'fg-white': colors.base.white,
    'fg-disabled': colors.grayLight[400],
    'fg-disabled-subtle': colors.grayLight[300],
    'fg-brand-primary': colors.brand[600],
    'fg-brand-primary-alt': colors.brand[600],
    'fg-brand-secondary': colors.brand[500],
    'fg-error-primary': colors.error[600],
    'fg-error-secondary': colors.error[500],
    'fg-warning-primary': colors.warning[600],
    'fg-warning-secondary': colors.warning[500],
    'fg-success-primary': colors.success[600],
    'fg-success-secondary': colors.success[500],
    'fg-featured-icon-brand': colors.brand[600],
    'fg-featured-icon-gray': colors.grayLight[500],
    'fg-featured-icon-error': colors.error[600],
    'fg-featured-icon-warning': colors.warning[600],
    'fg-featured-icon-success': colors.success[600],
    'fg-footer': colors.grayLight[200],
    'fg-footer-hover': colors.grayLight[400],

    /* Background color variables */
    'bg-primary': colors.base.white,
    'bg-primary-alt': colors.base.white,
    'bg-primary-hover': colors.grayLight[50],
    'bg-primary-solid': colors.grayLight[950],
    'bg-secondary': colors.grayLight[50],
    'bg-secondary-alt': colors.grayLight[50],
    'bg-secondary-hover': colors.grayLight[100],
    'bg-secondary-subtle': colors.grayLight[25],
    'bg-secondary-solid': colors.grayLight[600],
    'bg-tertiary': colors.grayLight[100],
    'bg-quaternary': colors.grayLight[200],
    'bg-active': colors.grayLight[50],
    'bg-disabled': colors.grayLight[100],
    'bg-disabled-subtle': colors.grayLight[50],
    'bg-overlay': colors.grayLight[950],
    'bg-brand-primary': colors.brand[50],
    'bg-brand-primary-alt': colors.brand[50],
    'bg-brand-secondary': colors.brand[100],
    'bg-brand-solid': colors.brand[600],
    'bg-brand-solid-hover': colors.brand[700],
    'bg-brand-section': colors.brand[800],
    'bg-brand-section-subtle': colors.brand[700],
    'bg-error-primary': colors.error[50],
    'bg-error-secondary': colors.error[100],
    'bg-error-solid': colors.error[600],
    'bg-warning-primary': colors.warning[50],
    'bg-warning-secondary': colors.warning[100],
    'bg-warning-solid': colors.warning[600],
    'bg-success-primary': colors.success[50],
    'bg-success-secondary': colors.success[100],
    'bg-success-solid': colors.success[600],

    /* Alpha color variables */
    'alpha-white-10': 'rgba(255, 255, 255, 0.1)',
    'alpha-white-20': 'rgba(255, 255, 255, 0.2)',
    'alpha-white-30': 'rgba(255, 255, 255, 0.3)',
    'alpha-white-40': 'rgba(255, 255, 255, 0.4)',
    'alpha-white-50': 'rgba(255, 255, 255, 0.5)',
    'alpha-white-60': 'rgba(255, 255, 255, 0.6)',
    'alpha-white-70': 'rgba(255, 255, 255, 0.7)',
    'alpha-white-80': 'rgba(255, 255, 255, 0.8)',
    'alpha-white-90': 'rgba(255, 255, 255, 0.9)',
    'alpha-white-100': 'rgba(255, 255, 255, 1)',
    'alpha-black-10': 'rgba(0, 0, 0, 0.1)',
    'alpha-black-20': 'rgba(0, 0, 0, 0.2)',
    'alpha-black-30': 'rgba(0, 0, 0, 0.3)',
    'alpha-black-40': 'rgba(0, 0, 0, 0.4)',
    'alpha-black-50': 'rgba(0, 0, 0, 0.5)',
    'alpha-black-60': 'rgba(0, 0, 0, 0.6)',
    'alpha-black-70': 'rgba(0, 0, 0, 0.7)',
    'alpha-black-80': 'rgba(0, 0, 0, 0.8)',
    'alpha-black-90': 'rgba(0, 0, 0, 0.9)',
    'alpha-black-100': 'rgba(0, 0, 0, 1)',

    /* Utility color variables */
    // base colors that could be inverted in dark mode
    'utility-gray-50': colors.grayLight[50],
    'utility-gray-100': colors.grayLight[100],
    'utility-gray-200': colors.grayLight[200],
    'utility-gray-300': colors.grayLight[300],
    'utility-gray-400': colors.grayLight[400],
    'utility-gray-500': colors.grayLight[500],
    'utility-gray-600': colors.grayLight[600],
    'utility-gray-700': colors.grayLight[700],
    'utility-gray-800': colors.grayLight[800],
    'utility-gray-900': colors.grayLight[900],

    'utility-brand-50': colors.brand[50],
    'utility-brand-50-alt': colors.brand[50],
    'utility-brand-100': colors.brand[100],
    'utility-brand-100-alt': colors.brand[100],
    'utility-brand-200': colors.brand[200],
    'utility-brand-200-alt': colors.brand[200],
    'utility-brand-300': colors.brand[300],
    'utility-brand-300-alt': colors.brand[300],
    'utility-brand-400': colors.brand[400],
    'utility-brand-400-alt': colors.brand[400],
    'utility-brand-500': colors.brand[500],
    'utility-brand-500-alt': colors.brand[500],
    'utility-brand-600': colors.brand[600],
    'utility-brand-600-alt': colors.brand[600],
    'utility-brand-700': colors.brand[700],
    'utility-brand-700-alt': colors.brand[700],
    'utility-brand-800': colors.brand[800],
    'utility-brand-800-alt': colors.brand[800],
    'utility-brand-900': colors.brand[900],
    'utility-brand-900-alt': colors.brand[900],

    'utility-error-50': colors.error[50],
    'utility-error-100': colors.error[100],
    'utility-error-200': colors.error[200],
    'utility-error-300': colors.error[300],
    'utility-error-400': colors.error[400],
    'utility-error-500': colors.error[500],
    'utility-error-600': colors.error[600],
    'utility-error-700': colors.error[700],

    'utility-success-50': colors.success[50],
    'utility-success-100': colors.success[100],
    'utility-success-200': colors.success[200],
    'utility-success-300': colors.success[300],
    'utility-success-400': colors.success[400],
    'utility-success-500': colors.success[500],
    'utility-success-600': colors.success[600],
    'utility-success-700': colors.success[700],

    'utility-warning-50': colors.warning[50],
    'utility-warning-100': colors.warning[100],
    'utility-warning-200': colors.warning[200],
    'utility-warning-300': colors.warning[300],
    'utility-warning-400': colors.warning[400],
    'utility-warning-500': colors.warning[500],
    'utility-warning-600': colors.warning[600],
    'utility-warning-700': colors.warning[700],
  }
}

export const dark: ThemeDefinition = {
  dark: true,
  colors: {
    // This is the default color palette for Vuetify.

    // 'background: #FFFFFF' would be interpolated as var(--v-theme-background) as 255, 255, 255
    // use inside rgb() or rgba() functions
    // rgba(var(--v-theme-background), 0.87)

    background: colors.grayDark[950],
    'on-background': colors.grayDark[50],
    surface: colors.grayDark[900],
    'on-surface': colors.grayDark[50],
    'surface-bright': colors.grayDark[950],
    'on-surface-bright': colors.grayDark[50],
    'surface-light': colors.grayDark[800],
    'on-surface-light': colors.grayDark[50],
    'surface-variant': colors.grayDark[900],
    'on-surface-variant': colors.grayDark[50],
    primary: colors.brand[500],
    'on-primary': colors.grayDark[50],
    'primary-darken-1': colors.brand[600],
    'on-primary-darken-1': colors.grayDark[50],
    secondary: colors.brand[500],
    'on-secondary': colors.grayDark[50],
    'secondary-darken-1': colors.brand[400],
    'on-secondary-darken-1': colors.grayDark[50],
    error: colors.error[500],
    'on-error': colors.grayDark[50],
    success: colors.success[500],
    'on-success': colors.grayDark[50],
    warning: colors.warning[500],
    'on-warning': colors.grayDark[50],
    'brand-section': colors.grayDark[800],
    'on-brand-section': colors.grayDark[50],
  },
  variables: {
    // This is the set of variables that defined in our design system.
    // also other non-color variables can be defined here.

    // 'my-crazy-variable': 42, would be interpolated as var(--v-my-crazy-variable)
    // colors would be interpolated as 255, 255, 255 and should be used inside rgb() or rgba() functions
    // rgba(var(--v-color-gray-950), 0.87)

    /* Override Vuetify opacity variables */
    'border-opacity': 0.12,
    'high-emphasis-opacity': 0.87,
    'medium-emphasis-opacity': 0.60,
    'disabled-opacity': 0.38,
    'idle-opacity': 0.04,
    'hover-opacity': 0,
    'focus-opacity': 0.12,
    'selected-opacity': 0.08,
    'activated-opacity': 0,
    'pressed-opacity': 0.12,
    'dragged-opacity': 0.08,

    /* Base colors */
    'color-base-white': colors.base.white,
    'color-base-black': colors.base.black,
    'color-base-transparent': colors.base.transparent,

    /* Gray colors */
    'color-gray-25': colors.grayDark[25],
    'color-gray-50': colors.grayDark[50],
    'color-gray-100': colors.grayDark[100],
    'color-gray-200': colors.grayDark[200],
    'color-gray-300': colors.grayDark[300],
    'color-gray-400': colors.grayDark[400],
    'color-gray-500': colors.grayDark[500],
    'color-gray-600': colors.grayDark[600],
    'color-gray-700': colors.grayDark[700],
    'color-gray-800': colors.grayDark[800],
    'color-gray-900': colors.grayDark[900],
    'color-gray-950': colors.grayDark[950],

    /* Brand colors */
    'color-brand-25': colors.brand[25],
    'color-brand-50': colors.brand[50],
    'color-brand-100': colors.brand[100],
    'color-brand-200': colors.brand[200],
    'color-brand-300': colors.brand[300],
    'color-brand-400': colors.brand[400],
    'color-brand-500': colors.brand[500],
    'color-brand-600': colors.brand[600],
    'color-brand-700': colors.brand[700],
    'color-brand-800': colors.brand[800],
    'color-brand-900': colors.brand[900],
    'color-brand-950': colors.brand[950],

    /* Error colors */
    'color-error-25': colors.error[25],
    'color-error-50': colors.error[50],
    'color-error-100': colors.error[100],
    'color-error-200': colors.error[200],
    'color-error-300': colors.error[300],
    'color-error-400': colors.error[400],
    'color-error-500': colors.error[500],
    'color-error-600': colors.error[600],
    'color-error-700': colors.error[700],
    'color-error-800': colors.error[800],
    'color-error-900': colors.error[900],
    'color-error-950': colors.error[950],

    /* Success colors */
    'color-success-25': colors.success[25],
    'color-success-50': colors.success[50],
    'color-success-100': colors.success[100],
    'color-success-200': colors.success[200],
    'color-success-300': colors.success[300],
    'color-success-400': colors.success[400],
    'color-success-500': colors.success[500],
    'color-success-600': colors.success[600],
    'color-success-700': colors.success[700],
    'color-success-800': colors.success[800],
    'color-success-900': colors.success[900],
    'color-success-950': colors.success[950],

    /* Warning colors */
    'color-warning-25': colors.warning[25],
    'color-warning-50': colors.warning[50],
    'color-warning-100': colors.warning[100],
    'color-warning-200': colors.warning[200],
    'color-warning-300': colors.warning[300],
    'color-warning-400': colors.warning[400],
    'color-warning-500': colors.warning[500],
    'color-warning-600': colors.warning[600],
    'color-warning-700': colors.warning[700],
    'color-warning-800': colors.warning[800],
    'color-warning-900': colors.warning[900],
    'color-warning-950': colors.warning[950],

    /* Text color variables */
    'text-primary': colors.grayDark[50],
    'text-primary-on-brand': colors.grayDark[50],
    'text-secondary': colors.grayDark[300],
    'text-secondary-hover': colors.grayDark[200],
    'text-secondary-on-brand': colors.grayDark[300],
    'text-tertiary': colors.grayDark[400],
    'text-tertiary-hover': colors.grayDark[300],
    'text-tertiary-on-brand': colors.grayDark[400],
    'text-quaternary': colors.grayDark[400],
    'text-quaternary-on-brand': colors.grayDark[400],
    'text-white': colors.base.white,
    'text-disabled': colors.grayDark[500],
    'text-placeholder': colors.grayDark[400],
    'text-placeholder-subtle': colors.grayDark[700],
    'text-brand-primary': colors.grayDark[50],
    'text-brand-secondary': colors.grayDark[300],
    'text-brand-tertiary': colors.grayDark[400],
    'text-brand-tertiary-alt': colors.grayDark[50],
    'text-error-primary': colors.error[400],
    'text-warning-primary': colors.warning[400],
    'text-success-primary': colors.success[400],

    /* Border color variables */
    'border-primary': colors.grayDark[700],
    'border-secondary': colors.grayDark[800],
    'border-tertiary': colors.grayDark[800],
    'border-disabled': colors.grayDark[700],
    'border-disabled-subtle': colors.grayDark[800],
    'border-brand': colors.brand[400],
    'border-brand-solid': colors.brand[500],
    'border-brand-solid-alt': colors.grayDark[700],
    'border-error': colors.error[400],
    'border-error-solid': colors.error[500],

    /* Foreground color variables */
    'fg-primary': colors.base.white,
    'fg-secondary': colors.grayDark[300],
    'fg-secondary-hover': colors.grayDark[200],
    'fg-tertiary': colors.grayDark[400],
    'fg-tertiary-hover': colors.grayDark[300],
    'fg-quaternary': colors.grayDark[400],
    'fg-quaternary-hover': colors.grayDark[300],
    'fg-quinary': colors.grayDark[500],
    'fg-quinary-hover': colors.grayDark[400],
    'fg-senary': colors.grayDark[600],
    'fg-white': colors.base.white,
    'fg-disabled': colors.grayDark[500],
    'fg-disabled-subtle': colors.grayDark[600],
    'fg-brand-primary': colors.brand[500],
    'fg-brand-primary-alt': colors.grayDark[300],
    'fg-brand-secondary': colors.brand[500],
    'fg-error-primary': colors.error[500],
    'fg-error-secondary': colors.error[400],
    'fg-warning-primary': colors.warning[500],
    'fg-warning-secondary': colors.warning[400],
    'fg-success-primary': colors.success[500],
    'fg-success-secondary': colors.success[400],
    'fg-featured-icon-brand': colors.brand[200],
    'fg-featured-icon-gray': colors.grayDark[200],
    'fg-featured-icon-error': colors.error[200],
    'fg-featured-icon-warning': colors.warning[200],
    'fg-featured-icon-success': colors.success[200],
    'fg-footer': colors.grayDark[200],
    'fg-footer-hover': colors.grayDark[400],

    /* Background color variables */
    'bg-primary': colors.grayDark[950],
    'bg-primary-alt': colors.grayDark[900],
    'bg-primary-hover': colors.grayDark[800],
    'bg-primary-solid': colors.grayDark[900],
    'bg-secondary': colors.grayDark[900],
    'bg-secondary-alt': colors.grayDark[950],
    'bg-secondary-hover': colors.grayDark[800],
    'bg-secondary-subtle': colors.grayDark[900],
    'bg-secondary-solid': colors.grayDark[600],
    'bg-tertiary': colors.grayDark[800],
    'bg-quaternary': colors.grayDark[700],
    'bg-active': colors.grayDark[800],
    'bg-disabled': colors.grayDark[800],
    'bg-disabled-subtle': colors.grayDark[900],
    'bg-overlay': colors.grayDark[800],
    'bg-brand-primary': colors.brand[500],
    'bg-brand-primary-alt': colors.grayDark[800],
    'bg-brand-secondary': colors.brand[600],
    'bg-brand-solid': colors.brand[600],
    'bg-brand-solid-hover': colors.brand[500],
    'bg-brand-section': colors.grayDark[800],
    'bg-brand-section-subtle': colors.grayDark[950],
    'bg-error-primary': colors.error[500],
    'bg-error-secondary': colors.error[600],
    'bg-error-solid': colors.error[600],
    'bg-warning-primary': colors.warning[500],
    'bg-warning-secondary': colors.warning[600],
    'bg-warning-solid': colors.warning[600],
    'bg-success-primary': colors.success[500],
    'bg-success-secondary': colors.success[600],
    'bg-success-solid': colors.success[600],

    /* Alpha color variables */
    'alpha-white-10': 'rgba(12, 17, 29, 0.1)',
    'alpha-white-20': 'rgba(12, 17, 29, 0.2)',
    'alpha-white-30': 'rgba(12, 17, 29, 0.3)',
    'alpha-white-40': 'rgba(12, 17, 29, 0.4)',
    'alpha-white-50': 'rgba(12, 17, 29, 0.5)',
    'alpha-white-60': 'rgba(12, 17, 29, 0.6)',
    'alpha-white-70': 'rgba(12, 17, 29, 0.7)',
    'alpha-white-80': 'rgba(12, 17, 29, 0.8)',
    'alpha-white-90': 'rgba(12, 17, 29, 0.9)',
    'alpha-white-100': 'rgba(12, 17, 29, 1)',
    'alpha-black-10': 'rgba(255, 255, 255, 0.1)',
    'alpha-black-20': 'rgba(255, 255, 255, 0.2)',
    'alpha-black-30': 'rgba(255, 255, 255, 0.3)',
    'alpha-black-40': 'rgba(255, 255, 255, 0.4)',
    'alpha-black-50': 'rgba(255, 255, 255, 0.5)',
    'alpha-black-60': 'rgba(255, 255, 255, 0.6)',
    'alpha-black-70': 'rgba(255, 255, 255, 0.7)',
    'alpha-black-80': 'rgba(255, 255, 255, 0.8)',
    'alpha-black-90': 'rgba(255, 255, 255, 0.9)',
    'alpha-black-100': 'rgba(255, 255, 255, 1)',

    /* Utility color variables */
    // base colors that could be inverted in dark mode
    'utility-gray-50': colors.grayDark[900],
    'utility-gray-100': colors.grayDark[800],
    'utility-gray-200': colors.grayDark[700],
    'utility-gray-300': colors.grayDark[700],
    'utility-gray-400': colors.grayDark[600],
    'utility-gray-500': colors.grayDark[500],
    'utility-gray-600': colors.grayDark[400],
    'utility-gray-700': colors.grayDark[300],
    'utility-gray-800': colors.grayDark[200],
    'utility-gray-900': colors.grayDark[100],

    'utility-brand-50': colors.brand[950],
    'utility-brand-50-alt': colors.grayDark[900],
    'utility-brand-100': colors.brand[900],
    'utility-brand-100-alt': colors.grayDark[800],
    'utility-brand-200': colors.brand[800],
    'utility-brand-200-alt': colors.grayDark[700],
    'utility-brand-300': colors.brand[700],
    'utility-brand-300-alt': colors.grayDark[700],
    'utility-brand-400': colors.brand[600],
    'utility-brand-400-alt': colors.grayDark[600],
    'utility-brand-500': colors.brand[500],
    'utility-brand-500-alt': colors.grayDark[500],
    'utility-brand-600': colors.brand[400],
    'utility-brand-600-alt': colors.grayDark[400],
    'utility-brand-700': colors.brand[300],
    'utility-brand-700-alt': colors.grayDark[300],
    'utility-brand-800': colors.brand[200],
    'utility-brand-800-alt': colors.grayDark[200],
    'utility-brand-900': colors.brand[100],
    'utility-brand-900-alt': colors.grayDark[100],

    'utility-error-50': colors.error[950],
    'utility-error-100': colors.error[900],
    'utility-error-200': colors.error[800],
    'utility-error-300': colors.error[700],
    'utility-error-400': colors.error[600],
    'utility-error-500': colors.error[500],
    'utility-error-600': colors.error[400],
    'utility-error-700': colors.error[300],

    'utility-success-50': colors.success[950],
    'utility-success-100': colors.success[900],
    'utility-success-200': colors.success[800],
    'utility-success-300': colors.success[700],
    'utility-success-400': colors.success[600],
    'utility-success-500': colors.success[500],
    'utility-success-600': colors.success[400],
    'utility-success-700': colors.success[300],

    'utility-warning-50': colors.warning[950],
    'utility-warning-100': colors.warning[900],
    'utility-warning-200': colors.warning[800],
    'utility-warning-300': colors.warning[700],
    'utility-warning-400': colors.warning[600],
    'utility-warning-500': colors.warning[500],
    'utility-warning-600': colors.warning[400],
    'utility-warning-700': colors.warning[300],
  }
}
